# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.29.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.29.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/abai/Documents/Gamedev/GlyphAtlas

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/abai/Documents/GameDev/GlyphAtlas

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.29.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.29.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/abai/Documents/GameDev/GlyphAtlas/CMakeFiles /Users/abai/Documents/GameDev/GlyphAtlas//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/abai/Documents/GameDev/GlyphAtlas/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FreeTypeTest

# Build rule for target.
FreeTypeTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FreeTypeTest
.PHONY : FreeTypeTest

# fast build rule for target.
FreeTypeTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/build
.PHONY : FreeTypeTest/fast

#=============================================================================
# Target rules for targets named RectAtlasTest

# Build rule for target.
RectAtlasTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RectAtlasTest
.PHONY : RectAtlasTest

# fast build rule for target.
RectAtlasTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/build
.PHONY : RectAtlasTest/fast

#=============================================================================
# Target rules for targets named GlyphAtlasTest

# Build rule for target.
GlyphAtlasTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GlyphAtlasTest
.PHONY : GlyphAtlasTest

# fast build rule for target.
GlyphAtlasTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/build
.PHONY : GlyphAtlasTest/fast

#=============================================================================
# Target rules for targets named GlyphAtlasTestTest

# Build rule for target.
GlyphAtlasTestTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GlyphAtlasTestTest
.PHONY : GlyphAtlasTestTest

# fast build rule for target.
GlyphAtlasTestTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/build
.PHONY : GlyphAtlasTestTest/fast

#=============================================================================
# Target rules for targets named FreeTypeTestTest

# Build rule for target.
FreeTypeTestTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FreeTypeTestTest
.PHONY : FreeTypeTestTest

# fast build rule for target.
FreeTypeTestTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTestTest.dir/build.make CMakeFiles/FreeTypeTestTest.dir/build
.PHONY : FreeTypeTestTest/fast

#=============================================================================
# Target rules for targets named TestGenerator

# Build rule for target.
TestGenerator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestGenerator
.PHONY : TestGenerator

# fast build rule for target.
TestGenerator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/build
.PHONY : TestGenerator/fast

Algorithms/Algorithms.o: Algorithms/Algorithms.cpp.o
.PHONY : Algorithms/Algorithms.o

# target to build an object file
Algorithms/Algorithms.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/Algorithms/Algorithms.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/Algorithms/Algorithms.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/Algorithms/Algorithms.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/Algorithms/Algorithms.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/Algorithms/Algorithms.cpp.o
.PHONY : Algorithms/Algorithms.cpp.o

Algorithms/Algorithms.i: Algorithms/Algorithms.cpp.i
.PHONY : Algorithms/Algorithms.i

# target to preprocess a source file
Algorithms/Algorithms.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/Algorithms/Algorithms.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/Algorithms/Algorithms.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/Algorithms/Algorithms.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/Algorithms/Algorithms.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/Algorithms/Algorithms.cpp.i
.PHONY : Algorithms/Algorithms.cpp.i

Algorithms/Algorithms.s: Algorithms/Algorithms.cpp.s
.PHONY : Algorithms/Algorithms.s

# target to generate assembly for a file
Algorithms/Algorithms.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/Algorithms/Algorithms.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/Algorithms/Algorithms.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/Algorithms/Algorithms.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/Algorithms/Algorithms.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/Algorithms/Algorithms.cpp.s
.PHONY : Algorithms/Algorithms.cpp.s

FileUtils/FileUtils.o: FileUtils/FileUtils.cpp.o
.PHONY : FileUtils/FileUtils.o

# target to build an object file
FileUtils/FileUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/FileUtils/FileUtils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/FileUtils/FileUtils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/FileUtils/FileUtils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/FileUtils/FileUtils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTestTest.dir/build.make CMakeFiles/FreeTypeTestTest.dir/FileUtils/FileUtils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/FileUtils/FileUtils.cpp.o
.PHONY : FileUtils/FileUtils.cpp.o

FileUtils/FileUtils.i: FileUtils/FileUtils.cpp.i
.PHONY : FileUtils/FileUtils.i

# target to preprocess a source file
FileUtils/FileUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/FileUtils/FileUtils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/FileUtils/FileUtils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/FileUtils/FileUtils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/FileUtils/FileUtils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTestTest.dir/build.make CMakeFiles/FreeTypeTestTest.dir/FileUtils/FileUtils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/FileUtils/FileUtils.cpp.i
.PHONY : FileUtils/FileUtils.cpp.i

FileUtils/FileUtils.s: FileUtils/FileUtils.cpp.s
.PHONY : FileUtils/FileUtils.s

# target to generate assembly for a file
FileUtils/FileUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/FileUtils/FileUtils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/FileUtils/FileUtils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/FileUtils/FileUtils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/FileUtils/FileUtils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTestTest.dir/build.make CMakeFiles/FreeTypeTestTest.dir/FileUtils/FileUtils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/FileUtils/FileUtils.cpp.s
.PHONY : FileUtils/FileUtils.cpp.s

FreeTypeWrapper/FreeTypeWrapper.o: FreeTypeWrapper/FreeTypeWrapper.cpp.o
.PHONY : FreeTypeWrapper/FreeTypeWrapper.o

# target to build an object file
FreeTypeWrapper/FreeTypeWrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTestTest.dir/build.make CMakeFiles/FreeTypeTestTest.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.o
.PHONY : FreeTypeWrapper/FreeTypeWrapper.cpp.o

FreeTypeWrapper/FreeTypeWrapper.i: FreeTypeWrapper/FreeTypeWrapper.cpp.i
.PHONY : FreeTypeWrapper/FreeTypeWrapper.i

# target to preprocess a source file
FreeTypeWrapper/FreeTypeWrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTestTest.dir/build.make CMakeFiles/FreeTypeTestTest.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.i
.PHONY : FreeTypeWrapper/FreeTypeWrapper.cpp.i

FreeTypeWrapper/FreeTypeWrapper.s: FreeTypeWrapper/FreeTypeWrapper.cpp.s
.PHONY : FreeTypeWrapper/FreeTypeWrapper.s

# target to generate assembly for a file
FreeTypeWrapper/FreeTypeWrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTestTest.dir/build.make CMakeFiles/FreeTypeTestTest.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/FreeTypeWrapper/FreeTypeWrapper.cpp.s
.PHONY : FreeTypeWrapper/FreeTypeWrapper.cpp.s

GlyphAtlasSrc/GlyphAtlas.o: GlyphAtlasSrc/GlyphAtlas.cpp.o
.PHONY : GlyphAtlasSrc/GlyphAtlas.o

# target to build an object file
GlyphAtlasSrc/GlyphAtlas.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/GlyphAtlasSrc/GlyphAtlas.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/GlyphAtlasSrc/GlyphAtlas.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/GlyphAtlasSrc/GlyphAtlas.cpp.o
.PHONY : GlyphAtlasSrc/GlyphAtlas.cpp.o

GlyphAtlasSrc/GlyphAtlas.i: GlyphAtlasSrc/GlyphAtlas.cpp.i
.PHONY : GlyphAtlasSrc/GlyphAtlas.i

# target to preprocess a source file
GlyphAtlasSrc/GlyphAtlas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/GlyphAtlasSrc/GlyphAtlas.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/GlyphAtlasSrc/GlyphAtlas.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/GlyphAtlasSrc/GlyphAtlas.cpp.i
.PHONY : GlyphAtlasSrc/GlyphAtlas.cpp.i

GlyphAtlasSrc/GlyphAtlas.s: GlyphAtlasSrc/GlyphAtlas.cpp.s
.PHONY : GlyphAtlasSrc/GlyphAtlas.s

# target to generate assembly for a file
GlyphAtlasSrc/GlyphAtlas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/GlyphAtlasSrc/GlyphAtlas.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/GlyphAtlasSrc/GlyphAtlas.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/GlyphAtlasSrc/GlyphAtlas.cpp.s
.PHONY : GlyphAtlasSrc/GlyphAtlas.cpp.s

GlyphAtlasSrc/GlyphTexture.o: GlyphAtlasSrc/GlyphTexture.cpp.o
.PHONY : GlyphAtlasSrc/GlyphTexture.o

# target to build an object file
GlyphAtlasSrc/GlyphTexture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/GlyphAtlasSrc/GlyphTexture.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/GlyphAtlasSrc/GlyphTexture.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/GlyphAtlasSrc/GlyphTexture.cpp.o
.PHONY : GlyphAtlasSrc/GlyphTexture.cpp.o

GlyphAtlasSrc/GlyphTexture.i: GlyphAtlasSrc/GlyphTexture.cpp.i
.PHONY : GlyphAtlasSrc/GlyphTexture.i

# target to preprocess a source file
GlyphAtlasSrc/GlyphTexture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/GlyphAtlasSrc/GlyphTexture.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/GlyphAtlasSrc/GlyphTexture.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/GlyphAtlasSrc/GlyphTexture.cpp.i
.PHONY : GlyphAtlasSrc/GlyphTexture.cpp.i

GlyphAtlasSrc/GlyphTexture.s: GlyphAtlasSrc/GlyphTexture.cpp.s
.PHONY : GlyphAtlasSrc/GlyphTexture.s

# target to generate assembly for a file
GlyphAtlasSrc/GlyphTexture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/GlyphAtlasSrc/GlyphTexture.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/GlyphAtlasSrc/GlyphTexture.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/GlyphAtlasSrc/GlyphTexture.cpp.s
.PHONY : GlyphAtlasSrc/GlyphTexture.cpp.s

GlyphAtlasSrc/Shelf.o: GlyphAtlasSrc/Shelf.cpp.o
.PHONY : GlyphAtlasSrc/Shelf.o

# target to build an object file
GlyphAtlasSrc/Shelf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/GlyphAtlasSrc/Shelf.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/GlyphAtlasSrc/Shelf.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/GlyphAtlasSrc/Shelf.cpp.o
.PHONY : GlyphAtlasSrc/Shelf.cpp.o

GlyphAtlasSrc/Shelf.i: GlyphAtlasSrc/Shelf.cpp.i
.PHONY : GlyphAtlasSrc/Shelf.i

# target to preprocess a source file
GlyphAtlasSrc/Shelf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/GlyphAtlasSrc/Shelf.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/GlyphAtlasSrc/Shelf.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/GlyphAtlasSrc/Shelf.cpp.i
.PHONY : GlyphAtlasSrc/Shelf.cpp.i

GlyphAtlasSrc/Shelf.s: GlyphAtlasSrc/Shelf.cpp.s
.PHONY : GlyphAtlasSrc/Shelf.s

# target to generate assembly for a file
GlyphAtlasSrc/Shelf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/GlyphAtlasSrc/Shelf.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/GlyphAtlasSrc/Shelf.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/GlyphAtlasSrc/Shelf.cpp.s
.PHONY : GlyphAtlasSrc/Shelf.cpp.s

Math/Rect.o: Math/Rect.cpp.o
.PHONY : Math/Rect.o

# target to build an object file
Math/Rect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/Math/Rect.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/Math/Rect.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/Math/Rect.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/Math/Rect.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTestTest.dir/build.make CMakeFiles/FreeTypeTestTest.dir/Math/Rect.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/Math/Rect.cpp.o
.PHONY : Math/Rect.cpp.o

Math/Rect.i: Math/Rect.cpp.i
.PHONY : Math/Rect.i

# target to preprocess a source file
Math/Rect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/Math/Rect.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/Math/Rect.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/Math/Rect.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/Math/Rect.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTestTest.dir/build.make CMakeFiles/FreeTypeTestTest.dir/Math/Rect.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/Math/Rect.cpp.i
.PHONY : Math/Rect.cpp.i

Math/Rect.s: Math/Rect.cpp.s
.PHONY : Math/Rect.s

# target to generate assembly for a file
Math/Rect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/Math/Rect.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/Math/Rect.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/Math/Rect.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/Math/Rect.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTestTest.dir/build.make CMakeFiles/FreeTypeTestTest.dir/Math/Rect.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/Math/Rect.cpp.s
.PHONY : Math/Rect.cpp.s

SimdUtfWrapper/SimdUtfWrapper.o: SimdUtfWrapper/SimdUtfWrapper.cpp.o
.PHONY : SimdUtfWrapper/SimdUtfWrapper.o

# target to build an object file
SimdUtfWrapper/SimdUtfWrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTestTest.dir/build.make CMakeFiles/FreeTypeTestTest.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.o
.PHONY : SimdUtfWrapper/SimdUtfWrapper.cpp.o

SimdUtfWrapper/SimdUtfWrapper.i: SimdUtfWrapper/SimdUtfWrapper.cpp.i
.PHONY : SimdUtfWrapper/SimdUtfWrapper.i

# target to preprocess a source file
SimdUtfWrapper/SimdUtfWrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTestTest.dir/build.make CMakeFiles/FreeTypeTestTest.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.i
.PHONY : SimdUtfWrapper/SimdUtfWrapper.cpp.i

SimdUtfWrapper/SimdUtfWrapper.s: SimdUtfWrapper/SimdUtfWrapper.cpp.s
.PHONY : SimdUtfWrapper/SimdUtfWrapper.s

# target to generate assembly for a file
SimdUtfWrapper/SimdUtfWrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTestTest.dir/build.make CMakeFiles/FreeTypeTestTest.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/SimdUtfWrapper/SimdUtfWrapper.cpp.s
.PHONY : SimdUtfWrapper/SimdUtfWrapper.cpp.s

Targets/FreeTypeTest.o: Targets/FreeTypeTest.cpp.o
.PHONY : Targets/FreeTypeTest.o

# target to build an object file
Targets/FreeTypeTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/Targets/FreeTypeTest.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTestTest.dir/build.make CMakeFiles/FreeTypeTestTest.dir/Targets/FreeTypeTest.cpp.o
.PHONY : Targets/FreeTypeTest.cpp.o

Targets/FreeTypeTest.i: Targets/FreeTypeTest.cpp.i
.PHONY : Targets/FreeTypeTest.i

# target to preprocess a source file
Targets/FreeTypeTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/Targets/FreeTypeTest.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTestTest.dir/build.make CMakeFiles/FreeTypeTestTest.dir/Targets/FreeTypeTest.cpp.i
.PHONY : Targets/FreeTypeTest.cpp.i

Targets/FreeTypeTest.s: Targets/FreeTypeTest.cpp.s
.PHONY : Targets/FreeTypeTest.s

# target to generate assembly for a file
Targets/FreeTypeTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTest.dir/build.make CMakeFiles/FreeTypeTest.dir/Targets/FreeTypeTest.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FreeTypeTestTest.dir/build.make CMakeFiles/FreeTypeTestTest.dir/Targets/FreeTypeTest.cpp.s
.PHONY : Targets/FreeTypeTest.cpp.s

Targets/GlyphAtlasTest.o: Targets/GlyphAtlasTest.cpp.o
.PHONY : Targets/GlyphAtlasTest.o

# target to build an object file
Targets/GlyphAtlasTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/Targets/GlyphAtlasTest.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/Targets/GlyphAtlasTest.cpp.o
.PHONY : Targets/GlyphAtlasTest.cpp.o

Targets/GlyphAtlasTest.i: Targets/GlyphAtlasTest.cpp.i
.PHONY : Targets/GlyphAtlasTest.i

# target to preprocess a source file
Targets/GlyphAtlasTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/Targets/GlyphAtlasTest.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/Targets/GlyphAtlasTest.cpp.i
.PHONY : Targets/GlyphAtlasTest.cpp.i

Targets/GlyphAtlasTest.s: Targets/GlyphAtlasTest.cpp.s
.PHONY : Targets/GlyphAtlasTest.s

# target to generate assembly for a file
Targets/GlyphAtlasTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTest.dir/build.make CMakeFiles/GlyphAtlasTest.dir/Targets/GlyphAtlasTest.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GlyphAtlasTestTest.dir/build.make CMakeFiles/GlyphAtlasTestTest.dir/Targets/GlyphAtlasTest.cpp.s
.PHONY : Targets/GlyphAtlasTest.cpp.s

Targets/RectAtlasTest.o: Targets/RectAtlasTest.cpp.o
.PHONY : Targets/RectAtlasTest.o

# target to build an object file
Targets/RectAtlasTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/Targets/RectAtlasTest.cpp.o
.PHONY : Targets/RectAtlasTest.cpp.o

Targets/RectAtlasTest.i: Targets/RectAtlasTest.cpp.i
.PHONY : Targets/RectAtlasTest.i

# target to preprocess a source file
Targets/RectAtlasTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/Targets/RectAtlasTest.cpp.i
.PHONY : Targets/RectAtlasTest.cpp.i

Targets/RectAtlasTest.s: Targets/RectAtlasTest.cpp.s
.PHONY : Targets/RectAtlasTest.s

# target to generate assembly for a file
Targets/RectAtlasTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RectAtlasTest.dir/build.make CMakeFiles/RectAtlasTest.dir/Targets/RectAtlasTest.cpp.s
.PHONY : Targets/RectAtlasTest.cpp.s

Targets/TestGenerator.o: Targets/TestGenerator.cpp.o
.PHONY : Targets/TestGenerator.o

# target to build an object file
Targets/TestGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/Targets/TestGenerator.cpp.o
.PHONY : Targets/TestGenerator.cpp.o

Targets/TestGenerator.i: Targets/TestGenerator.cpp.i
.PHONY : Targets/TestGenerator.i

# target to preprocess a source file
Targets/TestGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/Targets/TestGenerator.cpp.i
.PHONY : Targets/TestGenerator.cpp.i

Targets/TestGenerator.s: Targets/TestGenerator.cpp.s
.PHONY : Targets/TestGenerator.s

# target to generate assembly for a file
Targets/TestGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TestGenerator.dir/build.make CMakeFiles/TestGenerator.dir/Targets/TestGenerator.cpp.s
.PHONY : Targets/TestGenerator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FreeTypeTest"
	@echo "... FreeTypeTestTest"
	@echo "... GlyphAtlasTest"
	@echo "... GlyphAtlasTestTest"
	@echo "... RectAtlasTest"
	@echo "... TestGenerator"
	@echo "... Algorithms/Algorithms.o"
	@echo "... Algorithms/Algorithms.i"
	@echo "... Algorithms/Algorithms.s"
	@echo "... FileUtils/FileUtils.o"
	@echo "... FileUtils/FileUtils.i"
	@echo "... FileUtils/FileUtils.s"
	@echo "... FreeTypeWrapper/FreeTypeWrapper.o"
	@echo "... FreeTypeWrapper/FreeTypeWrapper.i"
	@echo "... FreeTypeWrapper/FreeTypeWrapper.s"
	@echo "... GlyphAtlasSrc/GlyphAtlas.o"
	@echo "... GlyphAtlasSrc/GlyphAtlas.i"
	@echo "... GlyphAtlasSrc/GlyphAtlas.s"
	@echo "... GlyphAtlasSrc/GlyphTexture.o"
	@echo "... GlyphAtlasSrc/GlyphTexture.i"
	@echo "... GlyphAtlasSrc/GlyphTexture.s"
	@echo "... GlyphAtlasSrc/Shelf.o"
	@echo "... GlyphAtlasSrc/Shelf.i"
	@echo "... GlyphAtlasSrc/Shelf.s"
	@echo "... Math/Rect.o"
	@echo "... Math/Rect.i"
	@echo "... Math/Rect.s"
	@echo "... SimdUtfWrapper/SimdUtfWrapper.o"
	@echo "... SimdUtfWrapper/SimdUtfWrapper.i"
	@echo "... SimdUtfWrapper/SimdUtfWrapper.s"
	@echo "... Targets/FreeTypeTest.o"
	@echo "... Targets/FreeTypeTest.i"
	@echo "... Targets/FreeTypeTest.s"
	@echo "... Targets/GlyphAtlasTest.o"
	@echo "... Targets/GlyphAtlasTest.i"
	@echo "... Targets/GlyphAtlasTest.s"
	@echo "... Targets/RectAtlasTest.o"
	@echo "... Targets/RectAtlasTest.i"
	@echo "... Targets/RectAtlasTest.s"
	@echo "... Targets/TestGenerator.o"
	@echo "... Targets/TestGenerator.i"
	@echo "... Targets/TestGenerator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

